### ISSUE TITLE
Publish newer version

### ISSUE THREAD

**Issue by coder543** [Centril/dbg#1]
RUST_DBG_COMPACT doesn't seem to work on the latest published version of `dbg`, but it does work if I depend directly on this git repository.

**Comment by Centril** [comment]
Strange... I checked:

+ https://github.com/Centril/dbg/blob/master/src/lib.rs

against:

+ https://docs.rs/dbg/1.0.4/src/dbg/lib.rs.html

and there doesn't seem to be any diff (checked with `diff`).
Are you sure you are on version 1.0.4?

**Comment by coder543** [comment]
I may have made a mistake, I was in a bit of a rush at the time!

**Comment by coder543** [comment]
yep, I just confirmed over here. I had thought the environment variable was checked at run time, but it looks like it is checked at compile time... which honestly is even better and makes me sad that the RFC reviewers don't like it. No runtime cost, and you still get a choice of format.
